# Generated by Django 2.2.6 on 2020-03-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0007_auto_20200309_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='kunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_kunjungan', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Kunjungan')),
                ('jenis_kunjungan', models.CharField(blank=True, choices=[('B', 'Baru'), ('L', 'Lama')], default='B', max_length=1, verbose_name='Jenis Kunjungan')),
                ('jenis_dokter', models.CharField(blank=True, choices=[('U', 'Umum'), ('S', 'Spesialis'), ('G', 'Gigi')], default='U', max_length=10, verbose_name='Jenis Dokter')),
                ('last_update', models.DateField(auto_now=True)),
                ('id_dokter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.dokter', verbose_name='Dokter')),
                ('id_pasien', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.pasien', verbose_name='Nama Pasien')),
            ],
            options={
                'verbose_name': 'Kunjungan',
                'verbose_name_plural': 'Kunjungan',
            },
        ),
        migrations.CreateModel(
            name='tindakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_tindakan', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Tindakan')),
                ('last_update', models.DateField(auto_now=True)),
                ('id_dokter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.dokter', verbose_name='Dokter')),
                ('id_kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.kunjungan', verbose_name='Nomor Kunjungan')),
                ('jasa_medik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.jasa_medis', verbose_name='Jasa Medis')),
            ],
            options={
                'verbose_name': 'Tindakan',
                'verbose_name_plural': 'Tindakan',
            },
        ),
    ]
