# Generated by Django 2.2.6 on 2020-03-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='golongan_obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golongan', models.CharField(max_length=50, verbose_name='Golongan')),
            ],
            options={
                'verbose_name': 'Golongan Obat',
                'verbose_name_plural': 'Golongan Obat',
            },
        ),
        migrations.CreateModel(
            name='obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=30, verbose_name='Nama')),
                ('stok_obat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Stok')),
                ('harga_beli_box', models.IntegerField(blank=True, null=True, verbose_name='Harga Beli Box')),
                ('isi_box', models.IntegerField(blank=True, null=True, verbose_name='Isi Box')),
                ('harga_beli', models.IntegerField(blank=True, null=True, verbose_name='Harga Beli')),
                ('harga_jual', models.IntegerField(blank=True, null=True, verbose_name='Harga Jual')),
                ('exp_date', models.DateTimeField(blank=True, null=True, verbose_name='Exp Date')),
                ('apotik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apotik')),
                ('last_update', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_golongan_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.golongan_obat', verbose_name='Golongan')),
            ],
            options={
                'verbose_name': 'Obat',
                'verbose_name_plural': 'Obat',
            },
        ),
    ]
