# Generated by Django 2.2.6 on 2020-03-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jenis_penyakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50, verbose_name='Jenis Penyakit')),
            ],
            options={
                'verbose_name': 'Jenis Penyakit',
                'verbose_name_plural': 'Jenis Penyakit',
            },
        ),
        migrations.CreateModel(
            name='penyakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=25, verbose_name='Kode Penyakit')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Penyakit')),
                ('id_jenis_penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.jenis_penyakit', verbose_name='Jenis Penyakit')),
            ],
            options={
                'verbose_name': 'Penyakit',
                'verbose_name_plural': 'Penyakit',
            },
        ),
    ]
