# Generated by Django 2.2.6 on 2020-03-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_jenis_penyakit_penyakit'),
    ]

    operations = [
        migrations.CreateModel(
            name='tindakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tindakan', models.CharField(max_length=255, verbose_name='Jenis Tindakan')),
            ],
            options={
                'verbose_name': 'Jenis Tindakan',
                'verbose_name_plural': 'Jenis Tindakan',
            },
        ),
        migrations.CreateModel(
            name='jasa_medis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pelayanan', models.CharField(max_length=200, verbose_name='Jenis Pelayanan')),
                ('jasa_sarana', models.IntegerField(blank=True, null=True, verbose_name='Jasa Sarana')),
                ('jasa_pembinaan', models.IntegerField(blank=True, null=True, verbose_name='Jasa Pembinaan')),
                ('jasa_pelayanan', models.IntegerField(blank=True, null=True, verbose_name='Jasa Pelayanan')),
                ('tarif_total', models.IntegerField(blank=True, null=True, verbose_name='Total')),
                ('id_jenis_penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.tindakan', verbose_name='Tindakan')),
            ],
            options={
                'verbose_name': 'Jasa Medis',
                'verbose_name_plural': 'Jasa Medis',
            },
        ),
    ]
