# Generated by Django 2.2.6 on 2020-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30, verbose_name='Nama')),
                ('jenis', models.CharField(blank=True, choices=[('U', 'Umum'), ('S', 'Spesialis'), ('G', 'Gigi')], default='U', max_length=10, verbose_name='Jenis Dokter')),
                ('alamat', models.TextField(blank=True, max_length=200, verbose_name='Alamat')),
                ('no_telp', models.CharField(blank=True, max_length=20, verbose_name='Telp')),
                ('tarif', models.IntegerField(blank=True, null=True, verbose_name='Tarif Dokter')),
            ],
            options={
                'verbose_name': 'Dokter',
                'verbose_name_plural': 'Dokter',
            },
        ),
        migrations.CreateModel(
            name='pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_medrek', models.CharField(max_length=20, verbose_name='No. Medrek')),
                ('no_kartu_bpjs', models.CharField(blank=True, max_length=30, verbose_name='No. BPJS')),
                ('nama', models.CharField(max_length=30, verbose_name='Nama')),
                ('tgl_lahir', models.DateField(blank=True, verbose_name='Tgl Lahir')),
                ('tempat_lahir', models.CharField(blank=True, max_length=30, verbose_name='Tempat Lahir')),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'PRIA'), ('W', 'WANITA')], default='L', max_length=1, verbose_name='Jenis Kelamin')),
                ('alamat', models.TextField(blank=True, max_length=200, verbose_name='Alamat')),
                ('no_telp', models.CharField(blank=True, max_length=20, verbose_name='Telp')),
                ('jenis', models.CharField(blank=True, choices=[('U', 'Umum'), ('B', 'BPJS')], default='B', max_length=10, verbose_name='Jenis Pasien')),
            ],
            options={
                'verbose_name': 'Biodata Pasien',
                'verbose_name_plural': 'Pasien',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
