# Generated by Django 2.2.6 on 2020-03-09 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20200309_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='jenis_tindakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tindakan', models.CharField(max_length=255, verbose_name='Jenis Tindakan')),
                ('last_update', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jenis Tindakan',
                'verbose_name_plural': 'Jenis Tindakan',
            },
        ),
        migrations.RemoveField(
            model_name='jasa_medis',
            name='id_jenis_penyakit',
        ),
        migrations.AddField(
            model_name='dokter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokter',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jasa_medis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jasa_medis',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jenis_penyakit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jenis_penyakit',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasien',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='penyakit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penyakit',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='tindakan',
        ),
        migrations.AddField(
            model_name='jasa_medis',
            name='id_jenis_tindakan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.jenis_tindakan', verbose_name='Jenis Tindakan'),
            preserve_default=False,
        ),
    ]
