# Generated by Django 2.2.6 on 2020-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20200309_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
